services:
  # Ton application Laravel
  app:
    build: .
    ports:
      - "8080:80" # Ton site sera sur http://localhost:8080
      - "5173:5173" # Ajoute cette ligne pour exposer le port de Vite
    volumes:
      - .:/var/www/html
    networks:
      - laravel-network

  # Ta base de données MySQL
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_DATABASE} # Il va lire ton fichier .env
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel-network

  # phpMyAdmin pour gérer ta base de données via une interface web
  phpmyadmin:
    image: phpmyadmin
    container_name: cvcrud-phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 300M
    ports:
      - "8081:80"
    networks:
      - laravel-network      

networks:
  laravel-network:
    driver: bridge